/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import clases.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author PRIDE OMEGA
 */
public class NuevasMedidasPaciente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoPaciente
     */
    private int pcID;
    private String nombreGlobal;
    public NuevasMedidasPaciente() {
        initComponents();
        this.setLocationRelativeTo(null);
        ejemplo.setVisible(false);
        this.setTitle("Agregar medidas");
    }
    public NuevasMedidasPaciente(int pID) throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Agregar medidas");
        
        ejemplo.setVisible(false);
        pcID = pID;
        setFalseData(pID);
    }
    
    private void setFalseData(int pacID) throws SQLException{
        System.err.println("Vamos a cargar nombre y eso del paciente "+pacID);
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        Conexion conn = new Conexion();
        Connection con  = conn.getConnection();
        
        String sqlQuery = "select Nombre_completo,Genero,Edad from  pacientes where ID_Paciente = "+pacID;
        
        ps = con.prepareStatement(sqlQuery);
        rs = ps.executeQuery();
        
        if(rs.next()){
            nombreGlobal = rs.getObject(1).toString();
            NameField.setText(rs.getObject(1).toString());
            genderField.setText(rs.getObject(2).toString());
            ageField.setText(rs.getObject(3).toString());
        }
    }
    
    private void postData(String imc, String imm, String peso, String cintura, String brazo, String estatura, String fecha) throws SQLException{
        PreparedStatement ps = null;
        
        Conexion conn = new Conexion();
        Connection con  = conn.getConnection();
        
        
        String sqlQuery = "insert into medidas values(null,"+pcID+",'"+imc+"','"+imm+"','"+peso+"','"+cintura+"','"+brazo+"','"+estatura+"');";
        
        ps = con.prepareStatement(sqlQuery);
        
        int a = ps.executeUpdate();
        
        if(a == 1){
            //Aquí añadimos todo correcto xd
            JOptionPane.showMessageDialog(null, "Agregaste correctamente las nuevas medidas para "+nombreGlobal+"\nAhora se actualizaran sus fechas y citas hasta el momento","Agregado Correctamente",JOptionPane.INFORMATION_MESSAGE);
            
            
            int count = getCitasCount(); //Esto nos regresa el valor de la ultima cita por ejemplo un 1 o si no hay citas previas un 0
            int medidaID = getID_Medida(pcID); //Este regresa el ID con el mismo metodo anterior
            System.out.println("Actualizando fechas: contador de citas= "+count+" Y, medida id = "+medidaID);
            //Lanzamos los valores a updateFecha
            updateFechas(count,medidaID,fecha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ageField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        IMCField = new javax.swing.JTextField();
        IMMField = new javax.swing.JTextField();
        cinturaField = new javax.swing.JTextField();
        brazoField = new javax.swing.JTextField();
        estaturaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pesoField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tipoPaciente = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ejemplo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/error.png"))); // NOI18N
        jLabel1.setToolTipText("Salir");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        NameField.setEditable(false);
        NameField.setBackground(new java.awt.Color(153, 153, 153));
        NameField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        NameField.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 398, 38));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 626, 10));

        ageField.setEditable(false);
        ageField.setBackground(new java.awt.Color(153, 153, 153));
        ageField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        ageField.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 52, 38));

        genderField.setEditable(false);
        genderField.setBackground(new java.awt.Color(153, 153, 153));
        genderField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        genderField.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(genderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 52, 38));

        IMCField.setBackground(new java.awt.Color(153, 153, 153));
        IMCField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        IMCField.setForeground(new java.awt.Color(255, 255, 255));
        IMCField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IMCFieldKeyTyped(evt);
            }
        });
        jPanel1.add(IMCField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 163, 52, 38));

        IMMField.setBackground(new java.awt.Color(153, 153, 153));
        IMMField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        IMMField.setForeground(new java.awt.Color(255, 255, 255));
        IMMField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IMMFieldKeyTyped(evt);
            }
        });
        jPanel1.add(IMMField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 219, 52, 38));

        cinturaField.setBackground(new java.awt.Color(153, 153, 153));
        cinturaField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cinturaField.setForeground(new java.awt.Color(255, 255, 255));
        cinturaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cinturaFieldKeyTyped(evt);
            }
        });
        jPanel1.add(cinturaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 163, 52, 38));

        brazoField.setBackground(new java.awt.Color(153, 153, 153));
        brazoField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        brazoField.setForeground(new java.awt.Color(255, 255, 255));
        brazoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                brazoFieldKeyTyped(evt);
            }
        });
        jPanel1.add(brazoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 219, 52, 38));

        estaturaField.setBackground(new java.awt.Color(153, 153, 153));
        estaturaField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        estaturaField.setForeground(new java.awt.Color(255, 255, 255));
        estaturaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                estaturaFieldKeyTyped(evt);
            }
        });
        jPanel1.add(estaturaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 275, 52, 38));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Género");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("IMC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 172, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("IMM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 228, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Cintura");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 172, -1, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Estatura");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 284, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Brazo");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 228, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/flecha-izquierda (1).png"))); // NOI18N
        jLabel2.setToolTipText("Regresar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/mas.png"))); // NOI18N
        jLabel8.setToolTipText("Agregar");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/agregar.png"))); // NOI18N
        jLabel13.setToolTipText("Agregar");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 374, -1, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/error.png"))); // NOI18N
        jLabel12.setToolTipText("Cancelar");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/Cancelar.png"))); // NOI18N
        jLabel14.setToolTipText("Cancelar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 374, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel15.setText("Peso");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 284, -1, -1));

        pesoField.setBackground(new java.awt.Color(153, 153, 153));
        pesoField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        pesoField.setForeground(new java.awt.Color(255, 255, 255));
        pesoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesoFieldKeyTyped(evt);
            }
        });
        jPanel1.add(pesoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 275, 52, 38));

        jLabel17.setBackground(new java.awt.Color(197, 152, 38));
        jLabel17.setOpaque(true);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 30));

        tipoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/save.jpeg"))); // NOI18N
        jPanel1.add(tipoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 64, 70));

        dateField.setBackground(new java.awt.Color(153, 153, 153));
        dateField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        dateField.setForeground(new java.awt.Color(255, 255, 255));
        dateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateFieldFocusLost(evt);
            }
        });
        jPanel1.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 100, 38));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel18.setText("Fecha");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        ejemplo.setBackground(new java.awt.Color(197, 152, 38));
        ejemplo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ejemplo.setForeground(new java.awt.Color(255, 51, 51));
        ejemplo.setText("Ej. 10-ENE-22");
        jPanel1.add(ejemplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Main mn = null;
        try {
            mn = new Main();
        } catch (Exception ex) {
            Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        mn.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        try {
            // TODO add your handling code here:
            checkData();
        } catch (SQLException ex) {
            Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "¿Cancelar paciente nuevo?","Cancelar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(i == JOptionPane.YES_OPTION){
            Main mn = null;
            try {
                mn = new Main();
            } catch (Exception ex) {
                Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
            mn.setVisible(true);
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        try {
            // TODO add your handling code here:
            checkData();
        } catch (SQLException ex) {
            Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void dateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFieldFocusGained
        // TODO add your handling code here:
        ejemplo.setVisible(true);
    }//GEN-LAST:event_dateFieldFocusGained

    private void dateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateFieldFocusLost
        // TODO add your handling code here:
        ejemplo.setVisible(false);
    }//GEN-LAST:event_dateFieldFocusLost

    private void IMCFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMCFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_IMCFieldKeyTyped

    private void IMMFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IMMFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_IMMFieldKeyTyped

    private void pesoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesoFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_pesoFieldKeyTyped

    private void cinturaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinturaFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_cinturaFieldKeyTyped

    private void brazoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brazoFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_brazoFieldKeyTyped

    private void estaturaFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_estaturaFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_estaturaFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevasMedidasPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevasMedidasPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IMCField;
    private javax.swing.JTextField IMMField;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField ageField;
    private javax.swing.JTextField brazoField;
    private javax.swing.JTextField cinturaField;
    private javax.swing.JTextField dateField;
    private javax.swing.JLabel ejemplo;
    private javax.swing.JTextField estaturaField;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pesoField;
    private javax.swing.JLabel tipoPaciente;
    // End of variables declaration//GEN-END:variables
    
    private void checkData() throws SQLException{
       //pcID id paciente
       String imc = IMCField.getText();
       String imm = IMMField.getText();
       String peso = pesoField.getText();
       String cintura = cinturaField.getText();
       String brazo = brazoField.getText();
       String estatura = estaturaField.getText();
       String fecha = dateField.getText();
       
       if( imc.isEmpty() || imm.isEmpty() || peso.isEmpty() || cintura.isEmpty() || brazo.isEmpty() || estatura.isEmpty() || fecha.isEmpty()){
           JOptionPane.showMessageDialog(null, "Recuerda agregar todos los campos","Recordatorio",JOptionPane.ERROR_MESSAGE);
       }else{
           postData(imc,imm,peso,cintura,brazo,estatura,fecha);
       }
    }

    private int getCitasCount() throws SQLException {
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        Conexion conn = new Conexion();
        Connection con  = conn.getConnection();
        
        String sqlQuery = "select * from medidas where ID_Paciente ="+pcID;
        
        ps = con.prepareStatement(sqlQuery);
        rs = ps.executeQuery();
        
        if(rs.next()){
            int count = 1;
            while(rs.next()){
                count++;
            }
            return count;
        }else{
            return 0;
        }
       
    }

    private void updateFechas(int count, int medidaID, String fecha) throws SQLException {
        
        /*System.err.println("Vamos a agregar una nueva fecha!----------");
        System.err.println("Los valores son: Fecha = "+fecha);
        System.err.println("El id del paciente es: "+pcID);
        System.err.println("MedidaID = "+medidaID);
        System.err.println("Y esta fecha es la numero: "+count);*/
        
        PreparedStatement ps = null;
        
        
        Conexion conn = new Conexion();
        Connection con  = conn.getConnection();
                                                    //null,    fecha,     id_pac,   id_med,     citaNum
        String sqlQuery = "insert into fechas values (null, '"+fecha+"', "+pcID+","+medidaID+","+count+");";
        
        ps = con.prepareStatement(sqlQuery);
        int mod = ps.executeUpdate();
        if(mod == 1){
            JOptionPane.showMessageDialog(null, "Correcto!");
        }else{
            JOptionPane.showMessageDialog(null, "Algo salio mal");
        }
    }

    private int getID_Medida(int pcID) throws SQLException {
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        Conexion conn = new Conexion();
        Connection con  = conn.getConnection();
        String query = "select ID_Medida from medidas where ID_Paciente = "+pcID+" order by ID_Medida desc limit 1";
        ps = con.prepareStatement(query);
        rs = ps.executeQuery();
        if(rs.next()){
            int tmp = Integer.parseInt(rs.getObject(1).toString());
            con.close();
            return tmp;
        }
        return 0;
    }

  
        
    
    
    
}
