/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PRIDE OMEGA
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() throws InterruptedException {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCredits = new javax.swing.JLabel();
        txtValue = new javax.swing.JLabel();
        azul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main.setBackground(new java.awt.Color(229, 229, 229));
        Main.setPreferredSize(new java.awt.Dimension(731, 451));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/30_porciento-removebg-preview.png"))); // NOI18N
        Main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 330, 298));

        txtCredits.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtCredits.setForeground(new java.awt.Color(51, 51, 51));
        txtCredits.setText("Nutresa.. v1.0");
        Main.add(txtCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 349, -1, -1));

        txtValue.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        txtValue.setForeground(new java.awt.Color(255, 255, 255));
        txtValue.setText("Cargando...");
        Main.add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, -1, -1));

        azul.setBackground(new java.awt.Color(19, 21, 43));
        azul.setOpaque(true);
        azul.setPreferredSize(new java.awt.Dimension(280, 450));
        Main.add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(197, 152, 38));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(450, 70));
        Main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Splash sp = new Splash();
        sp.setVisible(true);
        
        try{
            for (int i = 0; i < 85; i++) {
                Thread.sleep(100);
                if(i==10){
                    sp.txtValue.setText("Cargando menus...");
                }
                if(i==20){
                    sp.txtValue.setText("Verificando pacientes...");
                }
                if(i == 30){
                    sp.txtValue.setText("Analizando datos...");
                }
                if(i == 50){
                    sp.txtValue.setText("Haciendo café...");
                }
                if(i == 60){
                    sp.txtValue.setText("Iniciando app...");
                }
            }
            
            Main mn = new Main();
            mn.setVisible(true);
            sp.dispose();
            
        }catch(Exception ex){
            
        }
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JLabel azul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtCredits;
    private javax.swing.JLabel txtValue;
    // End of variables declaration//GEN-END:variables
}
